server {
    listen 80;
    server_name home-budget.titerin.ovh;

    root /var/www/html/public;
    index index.php index.html;

    # -------------------------------
    # Cache des assets statiques
    # -------------------------------
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        expires 1M;
        add_header Cache-Control "public";
    }

    # -------------------------------
    # Requêtes Laravel
    # -------------------------------
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # -------------------------------
    # PHP via FPM
    # -------------------------------
    location ~ \.php$ {
        include fastcgi_params;

        # Nom du container PHP-FPM
        fastcgi_pass laravel-prod:9000;

        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # Pour gérer correctement les chemins Laravel
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # -------------------------------
    # Gestion des erreurs
    # -------------------------------
    error_page 404 /index.php;
    error_page 500 502 503 504 /index.php;

    # -------------------------------
    # Sécurité basique
    # -------------------------------
    location ~ /\.ht {
        deny all;
    }
}
