server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php index.html;

    # Assets Vite
    location /build/ {
        alias /var/www/html/public/build/;
        access_log off;
        log_not_found off;
    }

    # Fichiers statiques classiques
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        try_files $uri $uri/ /index.php?$query_string;
        access_log off;
        log_not_found off;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel-prod:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Toutes les autres requêtes
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}
